// For adding custom fonts with other frameworks, see:
// https://tailwindcss.com/docs/font-family

import type { Metadata } from "next";
import { Plus_Jakarta_Sans, Urbanist, Geist } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";

const geist = Geist({subsets:['latin'],variable:'--font-sans'});

const fontSerif = Urbanist({
  subsets: ["latin"],
  variable: "--font-serif",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={cn("font-sans", geist.variable)}>
      <body className={`${geist.variable} ${fontSerif.variable} antialiased`}>
        {children}
      </body>
    </html>
  );
}