export type TRANSACTIONS = {
  id: number;
  name: string;
  description: string;
  date: string;
  amount: number;
  category: "income" | "expense" | "investment" | "leisure";
};

export const TRANSACTIONS: TRANSACTIONS[] = [
  {
    id: 1,
    name: "Salary - January",
    description: "Monthly salary credited",
    date: "2025-01-05",
    amount: 85000,
    category: "income",
  },
  {
    id: 2,
    name: "Groceries",
    description: "Weekly supermarket shopping",
    date: "2025-01-07",
    amount: 3200,
    category: "expense",
  },
  {
    id: 3,
    name: "Mutual Fund SIP",
    description: "Monthly SIP investment",
    date: "2025-01-10",
    amount: 10000,
    category: "investment",
  },
  {
    id: 4,
    name: "Electricity Bill",
    description: "Home electricity payment",
    date: "2025-01-12",
    amount: 2400,
    category: "expense",
  },
  {
    id: 5,
    name: "Freelance UI Work",
    description: "Dashboard redesign project payment",
    date: "2025-01-15",
    amount: 22000,
    category: "income",
  },
  {
    id: 6,
    name: "Dinner Out",
    description: "Weekend dinner with friends",
    date: "2025-01-18",
    amount: 2600,
    category: "leisure",
  },
  {
    id: 7,
    name: "Stocks - Nifty ETF",
    description: "Bought ETF units",
    date: "2025-01-22",
    amount: 7000,
    category: "investment",
  },
  {
    id: 8,
    name: "Rent",
    description: "Monthly apartment rent",
    date: "2025-01-25",
    amount: 18000,
    category: "expense",
  },
  {
    id: 9,
    name: "Movie Night",
    description: "Cinema tickets and snacks",
    date: "2025-01-28",
    amount: 1800,
    category: "leisure",
  },
  {
    id: 10,
    name: "Salary - February",
    description: "Monthly salary credited",
    date: "2025-02-05",
    amount: 85000,
    category: "income",
  },
  {
    id: 11,
    name: "Groceries",
    description: "Weekly supermarket shopping",
    date: "2025-02-06",
    amount: 3400,
    category: "expense",
  },
  {
    id: 12,
    name: "Transport Pass",
    description: "Monthly commute pass",
    date: "2025-02-08",
    amount: 1500,
    category: "expense",
  },
  {
    id: 13,
    name: "Mutual Fund SIP",
    description: "Monthly SIP investment",
    date: "2025-02-10",
    amount: 10000,
    category: "investment",
  },
  {
    id: 14,
    name: "Weekend Trip",
    description: "Short getaway and stay",
    date: "2025-02-14",
    amount: 6200,
    category: "leisure",
  },
  {
    id: 15,
    name: "Freelance Landing Page",
    description: "Client payment for landing page work",
    date: "2025-02-16",
    amount: 18000,
    category: "income",
  },
  {
    id: 16,
    name: "Health Insurance",
    description: "Monthly premium",
    date: "2025-02-19",
    amount: 2800,
    category: "expense",
  },
  {
    id: 17,
    name: "Stocks - Large Cap Fund",
    description: "Added to long-term portfolio",
    date: "2025-02-22",
    amount: 9000,
    category: "investment",
  },
  {
    id: 18,
    name: "Dinner Out",
    description: "Dinner with family",
    date: "2025-02-26",
    amount: 2400,
    category: "leisure",
  },
];
