import DashboardProvider from "@/components/dashboard/dashboard-provider";

import { Urbanist } from "next/font/google";

import type { Metadata } from "next";
import DashboardNavbar from "@/components/dashboard/dashboard-navbar";

const fontSerif = Urbanist({
    subsets: ["latin"],
    variable: "--font-serif",
});

export const metadata: Metadata = {
    title: "Dashboard",
    description: "Generated by create next app",
    icons: {
        icon: "/logo.svg",
    },
};

export default function DashboardLayout({ children }: { children: React.ReactNode }) {
    return (
        <div className={`${fontSerif.variable} antialiased`}>
            <DashboardProvider>
                <DashboardNavbar />
                {children}
            </DashboardProvider>
        </div>
    );
}